<?php
// Copyright 1999-2018. Plesk International GmbH. All rights reserved.

$messages = [
    'form_restart_tutorial'              => 'Tutorial neu starten',
    'message_container'                  => '<div class="welcome-container">%%content%%</div>',
    'message_error_install'              => 'Installation fehlgeschlagen: %%error%% Sie können diesen Schritt überspringen!',
    'message_error_restart'              => 'Bitte wählen Sie die Checkbox aus um das Tutorial neu zu starten.',
    'message_introtext'                  => '<div class="welcome-introtext"><div class="welcome-title"><span class="close-button"><a href="%%close_link%%"><img src="%%close%%" /></a></span><h2>Willkommen bei Ihrem neuen Plesk WordPress Server</h2></div><div class="welcome-image-float"><img src="%%elvis%%" alt="Plesk - Octopus" /></div><div class="welcome-text"><p>Hallo %%name%%,</p><p>schön Sie kennenzulernen! Mein Name ist Elvis, ich werde Ihnen bei Ihren ersten Schritten mit Plesk behilflich sein.</p><p>Sie haben die richtige Entscheidung mit Ihrem WordPress Server gemacht, wenn Sie das beste Open-Source CMS für Ihre Projekte nutzen wollen.</p><p>Lassen Sie uns zusammen starten. Keine Angst, mit Plesk und meiner Hilfe ist es sehr einfach!</p></div></div><hr />',
    'message_step_domain'                => '<div class="welcome-active"><span class="icon-active icon-domain"></span><div class="welcome-step-container"><h3>Fügen Sie eine Domain hinzu</h3><p>Bevor wir starten, müssen Sie zuerst eine Domain hinzufügen. Dies können Sie <a href="%%link_domain%%">hier</a> erledigen.</p><p class="welcome-description">Sobald Sie eine Domain hinzugefügt haben, können wir WordPress installieren und optimieren. Bitte kehren Sie zu der Startseite zurück, wenn die Domain angelegt wurde.</p></div></div>',
    'message_step_install_full'          => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Erstellen Sie eine WordPress-Seite</h3><p>Installieren Sie Ihre <a href="%%link_install%%">neue WordPress Seite</a> oder importieren Sie Ihre <a href="%%link_migrate%%">bestehende WordPress-Seite</a>.</p><p class="welcome-description">Mit dem WordPress Toolkit können Sie Ihre WordPress Seite innerhalb weniger Minuten erstellen. Das Toolkit stellt Ihnen eine Vielzahl von Entwicklungsabläufen für WordPress Administratoren und Entwicklern zur Verfügung. Sowohl für Anfänger als auch Fortgeschrittene stehen verschiedene Tools zur Auswahl!</p></div></div>',
    'message_step_install_inactive'      => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-wptk"></span><div class="welcome-step-container"><h3>Erstellen Sie eine WordPress-Seite</h3><p>Installieren Sie eine neue WordPress Seite oder importieren Sie Ihre bestehende WordPress Installation.</p></div></div>',
    'message_step_install_new'           => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Erstellen Sie eine WordPress-Seite</h3><p>Installieren Sie eine <a href="%%link_install%%">neue WordPress Seite</a> mit dem WordPress Toolkit.</p><p class="welcome-description">Mit dem WordPress Toolkit können Sie Ihre WordPress Seite innerhalb weniger Minuten erstellen. Das Toolkit stellt Ihnen eine Vielzahl von Entwicklungsabläufen für WordPress Administratoren und Entwicklern zur Verfügung. Sowohl für Anfänger als auch Fortgeschrittene stehen verschiedene Tools zur Auswahl!</p><p>Oder wollen Sie Ihre bestehende WordPress-Seite importieren? Unsere Migrations-Extension Site Import ist leider nicht installiert. <a href="%%link_install_site_import%%">Installieren Sie die Migrations-Exstension Site Import</a> jetzt, wenn Sie eine bestehende Webseite importieren wollen. Dies kann ein paar Minuten in Anspruch nehmen.</p></div></div>',
    'message_step_install_not_wptoolkit' => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Erstellen Sie eine WordPress-Seite</h3><p>Oh, scheinbar ist das WordPress Toolkit nicht installiert. Bitte installieren Sie es von unserem <a href="%%link_install%%">Extension Katalog</a>, um direkt mit WordPress und Plesk zu starten!</p><p class="welcome-description">Mit dem WordPress Toolkit können Sie Ihre WordPress Seite innerhalb weniger Minuten erstellen. Das Toolkit stellt Ihnen eine Vielzahl von Entwicklungsabläufen für WordPress Administratoren und Entwicklern zur Verfügung. Sowohl für Anfänger als auch Fortgeschrittene stehen verschiedene Tools zur Auswahl!</p></div></div>',
    'message_step_pagespeed'             => '<div class="welcome-active"><span class="icon-active icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimieren Sie Ihre Webseite mit PageSpeed</h3><p>Prüfen Sie Ihre WordPress-Webseite mit <a href="%%link_pagespeed%%">PageSpeed Insights</a> und steigern Sie Ihre Webseiten-Performance mit Google PageSpeed für Apache.</p><p class="welcome-description">Mit PageSpeed Insights können Sie verschiedene Wege finden, um Ihre Webseite schneller und freundlicher für mobile Endgeräte zu machen. Dies ist auch ein wichtiger Schritt für eine bessere Positionierung bei Google. Das Tool analysiert den Inhalt Ihrer Webseite und liefert Ihnen Optimierungsratschläge.</p></div></div>',
    'message_step_pagespeed_inactive'    => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimieren Sie Ihre Webseite mit PageSpeed</h3><p>Prüfen Sie Ihre WordPress Webseite mit PageSpeed Insights und steigern Sie Ihre Webseiten-Performance mit Google PageSpeed für Apache.</p></div></div>',
    'message_step_pagespeed_not'         => '<div class="welcome-active"><span class="icon-active icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimieren Sie Ihre Webseite mit PageSpeed</h3><p>Oh, scheinbar ist die PageSpeed Insights Extension nicht installiert. Bitte <a href="%%link_install%%">installieren Sie PageSpeed Insights</a> jetzt, um Ihre WordPress-Webseite zu analysieren. Dies kann ein paar Minuten in Anspruch nehmen.</p><p class="welcome-description">Mit PageSpeed Insights können Sie verschiedene Wege finden, um Ihre Webseite schneller und freundlicher für mobile Endgeräte zu machen. Dies ist auch ein wichtiger Schritt für eine bessere Positionierung bei Google. Das Tool analysiert den Inhalt Ihrer Webseite und liefert Ihnen Optimierungsratschläge.</p></div></div>',
    'message_step_restart'               => '<div class="welcome-inactive welcome-done complete"><span class="icon-complete"></span><div class="welcome-step-container"><h3>Herzlichen Glückwunsch! Sie haben das Tutorial abgeschlossen.</h3><p>Wir wünschen Ihnen viel Spaß bei mit Ihrer WordPress-Webseite!</p><p>Wollen Sie das <a href="%%link_restart%%">Tutorial neu starten</a>? Sie können es auch komplett <a href="%%link_deactivate%%">deaktivieren</a>.</p></div></div>',
    'message_step_ssl'                   => '<div class="welcome-active"><span class="icon-active icon-security-advisor"></span><div class="welcome-step-container"><h3>
	Fügen Sie ein SSL-Zertifikat hinzu und sichern Sie Ihre Webseite</h3><p>
	Sichern Sie Ihre WordPress-Webseite mit unserem <a href="%%link_security%%">%%link_advisor_name%%</a>.</p><p class="welcome-description">Der %%link_advisor_name%% hilft Ihnen dabei, all Ihre Webseiten mit nur einem Klick mit SSL auszustatten. Darüber hinaus können Sie HTTP/2 für mehr Performance auf allen Webseiten aktivieren.</p></div></div>',
    'message_step_ssl_inactive'          => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-security-advisor"></span><div class="welcome-step-container"><h3>Fügen Sie ein SSL-Zertifikat hinzu und sichern Sie Ihre Webseite</h3><p>Erstellen Sie ein SSL Zertifikat mit der Hilfe von unserem %%link_advisor_name%%.</p></div></div>',
    'message_step_ssl_not'               => '<div class="welcome-active"><span class="icon-active icon-security-advisor"></span><div class="welcome-step-container"><h3>Fügen Sie ein SSL-Zertifikat hinzu und sichern Sie Ihre Webseite</h3><p>Oh, scheinbar ist die PageSpeed Insights Extension nicht installiert. Bitte <a href="%%link_install%%">installieren Sie %%link_advisor_name%%</a> jetzt, um Ihre WordPress Seiten abzusichern! Dies kann ein paar Minuten in Anspruch nehmen.</p><p class="welcome-description">Der %%link_advisor_name%% hilft Ihnen dabei, all Ihre Webseiten mit nur einem Klick mit SSL auszustatten. Darüber hinaus können Sie HTTP/2 für mehr Performance auf allen Webseiten aktivieren.</p></div></div>',
    'message_success_restart'            => 'Das Tutorial wurde erfolgreich neu gestartet.',
    'message_view_nothing_here'          => '<div><strong>Huhu, hier gibt es nichts zu sehen. ;) Sie finden mich auf der Hauptseite!</strong> - <em>Elvis</em><br /><img src="/modules/welcome-wp/images/plesk_octopus_generic.png" /></div>',
    'message_step_next'                  => '<div class="control"><hr /><p><small><strong><a href="%%link_next%%">Fertig? Für den nächsten Schritt hier klicken</a></strong></small> - <small><a href="%%link_deactivate%%">Tutorial deaktivieren</a></small></p></div>',
    'message_step_finish'                => '<div class="control"><hr /><p><small><a href="%%link_finish%%">Fertig? Hier klicken, um das Tutorial zu beenden</a></small></p></div>',
];
