<?php
// Copyright 1999-2018. Plesk International GmbH.

$messages = [
    'form_restart_tutorial'              => 'Restart the tutorial wizard',
    'message_container'                  => '<div class="welcome-container">%%content%%</div>',
    'message_error_install'              => 'Installation failed with error: %%error%% You can skip this step!',
    'message_error_restart'              => 'Please select the checkbox if you want to restart the tutorial!',
    'message_introtext'                  => '<div class="welcome-introtext"><div class="welcome-title"><span class="close-button"><a href="%%close_link%%"><img src="%%close%%" /></a></span><h2>Welcome to your new Plesk WordPress Server</h2></div><div class="welcome-image-float"><img src="%%elvis%%" alt="Plesk - Octopus" /></div><div class="welcome-text"><p>Hello %%name%%,</p><p>great to meet you! My name is Elvis Plesky, I will assist you in the beginning of your journey with Plesk.</p><p>You made the right decision with the WordPress Server if you want to use the best Open-Source CMS WordPress for your projects!</p><p>Let me help you to get started. Don\'t worry, it\'s easy with Plesk - and my help!</p></div></div><hr />',
    'message_step_domain'                => '<div class="welcome-active"><span class="icon-active icon-domain"></span><div class="welcome-step-container"><h3>Add a domain first</h3><p>You need to add at least one domain before we can start our tutorial! Go ahead and <a href="%%link_domain%%">create a new domain</a>.</p><p class="welcome-description">Once you\'ve created a domain, we can install and optimize your WordPress website. Please come back when the domain was created successfully!</p></div></div>',
    'message_step_install_full'          => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Create a WordPress website</h3><p>Install a <a href="%%link_install%%">new WordPress website</a> or import your <a href="%%link_migrate%%">existing WordPress instance</a>.</p><p class="welcome-description">With the WordPress Toolkit you create your WordPress website easily within minutes. The toolkit allows enabling a variety of development workflows for WordPress admins and developers of all skill levels, from beginners to pros. Install or import your first WordPress website now!</p></div></div>',
    'message_step_install_inactive'      => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-wptk"></span><div class="welcome-step-container"><h3>Create a WordPress website</h3><p>Install a new WordPress website or import your existing WordPress instance.</p></div></div>',
    'message_step_install_new'           => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Create a WordPress website</h3><p>Install a <a href="%%link_install%%">new WordPress website</a> with the WordPress Toolkit.</p><p class="welcome-description">With the WordPress Toolkit 
you create your WordPress website easily within minutes. The toolkit allows enabling a variety of development workflows for WordPress admins and developers of all skill levels, from beginners to pros. Install your first WordPress website now!</p><p>Or do you want to import an existing WordPress website? The Sie Import extension is not installed. <a href="%%link_install_site_import%%">Install Plesk Site Import</a> now if you want to import an existing website! This can take some minutes, please be patient.</p></div></div>',
    'message_step_install_not_wptoolkit' => '<div class="welcome-active"><span class="icon-active icon-wptk"></span><div class="welcome-step-container"><h3>Create a WordPress website</h3><p>Oh, seems that the WordPress Toolkit is not installed yet. Please install it directly from the <a href="%%link_install%%">Extension Catalog </a> to start your WordPress journey with Plesk!</p><p class="welcome-description">With the WordPress Toolkit you create your WordPress website easily within minutes. The toolkit allows enabling a variety of development workflows for WordPress admins and developers of all skill levels, from beginners to pros.</p></div></div>',
    'message_step_pagespeed'             => '<div class="welcome-active"><span class="icon-active icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimize your website with PageSpeed</h3><p>Check your WordPress website with <a href="%%link_pagespeed%%">PageSpeed Insights</a> and boost your website performance with Google PageSpeed for Apache.</p><p class="welcome-description">With PageSpeed Insights you can identify ways to make your site faster and more mobile-friendly. And this is also key to get a pole position in Google Search. The tool analyzes the delivered content of your website and suggests how to improve it.</p></div></div>',
    'message_step_pagespeed_inactive'    => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimize your website with PageSpeed</h3><p>Check your WordPress website with PageSpeed Insights and boost your website performance with Google PageSpeed for Apache.</p></div></div>',
    'message_step_pagespeed_not'         => '<div class="welcome-active"><span class="icon-active icon-pagespeed-insights"></span><div class="welcome-step-container"><h3>Optimize your website with PageSpeed</h3><p>Oh, seems that the PageSpeed Insights extension is not installed yet. <a href="%%link_install%%">Install PageSpeed Insights</a> now to analyze your WordPress website! This can take some minutes, please be patient.</p><p class="welcome-description">With PageSpeed Insights you can identify ways to make your site faster and more mobile-friendly. And this is also key to get a pole position in Google Search. The tool analyzes the delivered content of your website and suggests how to improve it.</p></div></div>',
    'message_step_restart'               => '<div class="welcome-inactive welcome-done complete"><span class="icon-complete"></span><div class="welcome-step-container"><h3>Congratulations! You made it through the tutorial.</h3><p>Now go and start working with your WordPress website!</p><p>Do you want to <a href="%%link_restart%%">restart the tutorial</a>? You also can <a href="%%link_deactivate%%">deactivate</a> it completely!</p></div></div>',
    'message_step_ssl'                   => '<div class="welcome-active"><span class="icon-active icon-security-advisor"></span><div class="welcome-step-container"><h3>Add an SSL certificate and secure your website</h3><p>Let\'s secure your WordPress website with the help of the <a href="%%link_security%%">%%link_advisor_name%%</a>.</p><p class="welcome-description">The %%link_advisor_name%% allows you to secure all your websites with SSL at one single click. Additionally, this extension lets you activate HTTP/2 for more performance on all your sites.</p></div></div>',
    'message_step_ssl_inactive'          => '<div class="welcome-inactive %%class%%"><span class="icon-%%class%% icon-security-advisor"></span><div class="welcome-step-container"><h3>Add an SSL certificate and secure your website</h3><p>Create an SSL certificate with the help of the %%link_advisor_name%%.</p></div></div>',
    'message_step_ssl_not'               => '<div class="welcome-active"><span class="icon-active icon-security-advisor"></span><div class="welcome-step-container"><h3>Add an SSL certificate and secure your website</h3><p>Oh, seems that the %%link_advisor_name%% extension is not installed yet. <a href="%%link_install%%">Install %%link_advisor_name%%</a> now to secure your WordPress website! This can take some minutes, please be patient.</p><p class="welcome-description">The %%link_advisor_name%% allows you to secure all your websites with SSL at one single click. Additionally, this extension lets you activate HTTP/2 for more performance on all your sites.</p></div></div>',
    'message_success_restart'            => 'The tutorial was restarted successfully!',
    'message_view_nothing_here'          => '<div><strong>Huhu, nothing to see here! Go to the Domains overview, there you will find me. :-)</strong> - <em>Elvis Plesky</em><br /><img src="/modules/welcome-wp/images/plesk_octopus_generic.png" /></div>',
    'message_step_next'                  => '<div class="control"><hr /><p><small><strong><a href="%%link_next%%">Done? Click for next step!</a></strong></small> - <small><a href="%%link_deactivate%%">No, please deactivate tutorial.</a></small></p></div>',
    'message_step_finish'                => '<div class="control"><hr /><p><small><a href="%%link_finish%%">Done? Click to finish the tutorial!</a></small></p></div>',
];
